name: maher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  equatable: 
  dartz:
  ffmpeg_kit_flutter_new_audio:
  flutter_bloc:
  flutter_svg:
  get_it:
  dio:
  skeletonizer:
  fluttertoast:
  shared_preferences:
  auto_route:
  formz:
  loader_overlay:
  flutter_foreground_task:
  path_provider:
  record:
  wakelock_plus:

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
