// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3AVvim2ZEofOJYFFKEi9sUw1y2l_9S9Q',
    appId: '1:22642361348:android:ff442cff8d4bb1391f6151',
    messagingSenderId: '22642361348',
    projectId: 'maher-c5bd9',
    storageBucket: 'maher-c5bd9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjTgwq4PjzS5MxYS8GpY4H0OJAh8Tu7c',
    appId: '1:22642361348:ios:f1e94194dd1053c61f6151',
    messagingSenderId: '22642361348',
    projectId: 'maher-c5bd9',
    storageBucket: 'maher-c5bd9.firebasestorage.app',
    androidClientId: '22642361348-3pgjqd9sk57b6puuvampepq26goneee0.apps.googleusercontent.com',
    iosClientId: '22642361348-7i9fds4vr58utkrev2622grni0dcjh13.apps.googleusercontent.com',
    iosBundleId: 'com.maher.app',
  );
}
